package gamilton;


import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adusha
 */
public class Frame extends javax.swing.JFrame {
    final int n = 5;
 
    int c[];   // номер хода, на котором посещается вершина
    int path[]; // номера посещаемых вершин
    int v0 = 2;    // начальная вершина
 
    //Матрица смежности
    int[][] a = {
        {0,1,1,0,0},
        {1,0,0,1,0},
        {1,0,0,1,0},
        {0,1,1,0,1},
        {0,0,1,1,0}
    };
    /**
     * Creates new form Frame
     */
    public Frame() {
        path = new int[n];
        c = new int[n];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_draw = new javax.swing.JPanel();
        btn_gamilton = new javax.swing.JButton();
        ed_path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gamilton");
        setMaximumSize(new java.awt.Dimension(553, 425));
        setMinimumSize(new java.awt.Dimension(553, 425));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout pnl_drawLayout = new javax.swing.GroupLayout(pnl_draw);
        pnl_draw.setLayout(pnl_drawLayout);
        pnl_drawLayout.setHorizontalGroup(
            pnl_drawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        pnl_drawLayout.setVerticalGroup(
            pnl_drawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        btn_gamilton.setText("Draw");
        btn_gamilton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gamiltonActionPerformed(evt);
            }
        });

        jButton1.setText("Gamilton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_draw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_gamilton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ed_path, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_draw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gamilton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ed_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gamiltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gamiltonActionPerformed
        Graphics g = pnl_draw.getGraphics();
        
        g.drawRect(0, 0, pnl_draw.getWidth() - 1, pnl_draw.getHeight() - 1);
        
        int cx = pnl_draw.getWidth() / 2;
        int cy = pnl_draw.getHeight() / 2;
        int radius = 120;
        int step = 360 / n;
        int sq_size = 20;
        int sq_size_div_2 = sq_size / 2;
        
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++) {
                if (a[i][j] != 0) {
                    float rad_from = (step * i * 3.14f) / 180 - (90 * 3.14f) / 180;
                    float rad_to = (step * j * 3.14f) / 180 - (90 * 3.14f) / 180;
                    int pos_x_from = (int) (radius * Math.cos(rad_from) + cx);
                    int pos_y_from = (int) (radius * Math.sin(rad_from) + cy);
                    int pos_x_to = (int) (radius * Math.cos(rad_to) + cx);
                    int pos_y_to = (int) (radius * Math.sin(rad_to) + cy);
                    
                    g.drawLine(pos_x_from + sq_size_div_2, pos_y_from + sq_size_div_2,
                            pos_x_to + sq_size_div_2, pos_y_to + sq_size_div_2);
                    g.clearRect(pos_x_from + 1, pos_y_from + 1, 
                            sq_size - 1, sq_size - 1);
                    g.clearRect(pos_x_to + 1, pos_y_to + 1, 
                            sq_size - 1, sq_size - 1);
                }
            }
        
        for(int i = 0; i < 360; i+= step) {
            // Смещаем положение меток на 90 назад, чтобы начало было
            // точно вверху циферблата.
            float rad = (i * 3.14f) / 180 - (90 * 3.14f) / 180;
            float pos_x = (float) (radius * Math.cos(rad) + cx);
            float pos_y = (float) (radius * Math.sin(rad) + cy);
            g.drawRect((int)pos_x, (int)pos_y, sq_size, sq_size);
            char[] text = Integer.toString(i / step).toCharArray();
            
            int nx = (int) (pos_x + g.getFontMetrics().charsWidth(text, 0, text.length) / 1.2);
            int ny = (int) (pos_y + g.getFontMetrics().getHeight() / 1.2);
            
            g.drawChars(text, 0, text.length, nx, ny);
        }
    }//GEN-LAST:event_btn_gamiltonActionPerformed

    private int gamilton(int k){
        int v, 
            q1 = 0;
        
        for(v = 0; v < n && q1 == 0; v++) {
          if(a[v][path[k-1]] != 0 || a[path[k-1]][v] != 0) {
                if (k == n &&  v == v0 )
                    q1 = 1;
                else 
                if (c[v] == -1) {
                    c[v] = k ; 
                    path[k] = v; 
                    q1 = gamilton(k+1);
                if (q1 == 0)
                    c[v]=-1;  
                }
            } 
        }
        
        return q1;
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int j = 0; j < n; j++)
            c[j] = -1;
        
        path[0] = v0;
        c[v0] = v0;
        
        int result = gamilton(1);
        
        if (result == 0) {
            ed_path.setText("No solution");
            return;
        }
        
        ed_path.setText("");
        for (int i = 0; i < path.length; i++)
            ed_path.setText(ed_path.getText() + Integer.toString(path[i]) + " ");
        
        ed_path.setText(ed_path.getText() + Integer.toString(path[0]));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gamilton;
    private javax.swing.JTextField ed_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnl_draw;
    // End of variables declaration//GEN-END:variables
}
